baseURL = 'https://hugo-theme-take-notes-example.pages.dev/'
languageCode = 'en-us'
title = 'Hugo theme take notes example'
sectionPagesMenu = "main"

[security]

[security.exec]
allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']

[markup]

[markup.highlight]
style = 'emacs'

[markup.asciidocExt.attributes]
toc = 'auto'            # Enable Asciidoctor TOC for Hugo
sectlinks = true        # Enable section title link

[module]

[[module.imports]]
path = 'hugo-theme-take-notes'
